In [2]:
import numpy as np

# From a list
cvalues = [20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]
data = np.array(cvalues)
print(data)

# Linspace examples
print(np.linspace(1, 10))          # 50 values between 1 and 10
print(np.linspace(1, 10, 7))       # 7 values
print(np.linspace(1, 10, 7, endpoint=False))  # Exclude endpoint

[20.1 20.8 21.9 22.5 22.7 22.3 21.8 21.2 20.9 20.1]
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [4]:
import numpy as np

# Zero matrix
zeros_arr = np.zeros((3, 4))
print("Zeros array:\n", zeros_arr)

# Constant value array (complex type)
complex_arr = np.full((3, 3), 6, dtype='complex')
print("Complex array:\n", complex_arr)

# Random array
random_arr = np.random.random((2, 2))
print("Random array:\n", random_arr)

Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Complex array:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]
Random array:
 [[0.97134297 0.53782156]
 [0.56245681 0.54887467]]
